In [1]:
import numpy as np

In [11]:
class equation():
    def __init__(self,A,D,b) :
        self.A=A;
        self.D=D;
        self.b=b;
    
    def get_BF(self):
        B=np.eye(3,3)-np.linalg.inv(self.D).dot(self.A);
        F=np.linalg.inv(self.D).dot(self.b);
        return B,F;

    def get_x(self,B,F):
        x=np.zeros((3,1),dtype=float);
        pre_x=x;
        x=B.dot(x)+F;
        print(x.round(4))
        while(np.max(abs(x-pre_x))>0.0001):
            pre_x=x;
            x=B.dot(x)+F;
            print(x.round(4))


In [12]:
A=np.array([[5,2,1],[-1,4,2],[2,-3,10]],dtype=float);
D=np.array([[5,0,0],[0,4,0],[0,0,10]],dtype=float);
b=np.array([[-12],[20],[3]],dtype=float);
n=equation(A,D,b);
B,F=n.get_BF()
n.get_x(B,F)

[[-2.4]
 [ 5. ]
 [ 0.3]]
[[-4.46]
 [ 4.25]
 [ 2.28]]
[[-4.556]
 [ 2.745]
 [ 2.467]]
[[-3.9914]
 [ 2.6275]
 [ 2.0347]]
[[-3.8579]
 [ 2.9848]
 [ 1.8865]]
[[-3.9712]
 [ 3.0922]
 [ 1.967 ]]
[[-4.0303]
 [ 3.0237]
 [ 2.0219]]
[[-4.0139]
 [ 2.9815]
 [ 2.0132]]
[[-3.9952]
 [ 2.99  ]
 [ 1.9972]]
[[-3.9954]
 [ 3.0026]
 [ 1.996 ]]
[[-4.0002]
 [ 3.0031]
 [ 1.9999]]
[[-4.0012]
 [ 3.    ]
 [ 2.001 ]]
[[-4.0002]
 [ 2.9992]
 [ 2.0002]]
[[-3.9997]
 [ 2.9998]
 [ 1.9998]]
[[-3.9999]
 [ 3.0002]
 [ 1.9999]]
[[-4.    ]
 [ 3.0001]
 [ 2.    ]]
[[-4.]
 [ 3.]
 [ 2.]]
[[-4.]
 [ 3.]
 [ 2.]]
